---
couchpotato:
  build: .
  container_name: couchpotato
  hostname: couchpotato
  domainname: kohlby.fr
  volumes:
    - /opt/ejson/keys:/opt/ejson/keys:ro
    - /mnt/docker/couchpotato:/data
    - /mnt/media:/media
  cap_add:
    - SYS_ADMIN
  user: root
  stdin_open: true
  tty: true
